# Navigation Links
main:
  - name: About
    url: /
    weight: 10
  - name: Experience
    url: /experience/
    weight: 20
  - name: My Blogs
    url: /my-blogs/
    weight: 30
  - name: Ongoing Projects
    url: /ongoing-projects/
    weight: 40
  - name: Projects
    url: /projects/
    weight: 50
  - name: Papers
    url: /papers/
    weight: 60
  - name: Talks
    url: /talks/
    weight: 70
  - name: Awards
    url: /awards/
    weight: 80
